// Files
const IFRAME_PAGE = 'mainPanel.html';

// Messaging
const FROM_IFRAME = 'FROM_IFRAME';
const SELECT_ELEMENTS = 'SELECT_ELEMENTS';
const BROWSER_ACTION_CLICKED = 'BROWSER_ACTION_CLICKED';
const TAB_UPDATED = 'TAB_UPDATED';
