// Files
export const MAIN_PANEL_PAGE = '/src/mainPanel/mainPanel.html';
export const DATA_PREVIEW = '/src/contentScripts/data/dataPreview.html';

// Messaging
export const Messages = Object.freeze({
    FROM_MAIN_PANEL: 'FROM_IFRAME',
    FROM_CONTROLLER: 'FROM_CONTROLLER',
    SELECTING_ROWS: 'SELECTING_ROWS',
    SELECTING_COLS: 'SELECTING_COLS',
    ADDED_COL: 'ADDED_COL',
    RENAMED_COL: 'RENAMED_COL',
    REMOVED_COL: 'REMOVED_COL',
    CHOSEN_COL: 'CHOSEN_COL',
    SELECTING_ELEMENTS: 'SELECTING_ELEMENTS',
    SELECTED: 'SELECTED',
    UNSELECTED: 'UNSELECTED',
    UNSELECTED_CURRENT: 'UNSELECTED_CURRENT',
    DECIDING_AUTO_SELECT: 'DECIDING_AUTO_SELECT',
    ACCEPT_AUTO_SELECT: 'ACCEPT_AUTO_SELECT',
    REJECT_AUTO_SELECT: 'REJECT_AUTO_SELECT',
    TEXT_SEARCH_CONTAINS: 'TEXT_SEARCH_CONTAINS',
    TEXT_SEARCH_STARTS: 'TEXT_SEARCH_STARTS',
    TEXT_SEARCH_ENDS: 'TEXT_SEARCH_ENDS',
    DOWNLOAD: 'DOWNLOAD',
    DISPLAY_PREVIEW: 'DISPLAY_PREVIEW',
    BROWSER_ACTION_CLICKED: 'BROWSER_ACTION_CLICKED',
    TAB_UPDATED: 'TAB_UPDATED'
});

// Others
export const ENTER_KEY = 13;

