// Files
export const MAIN_PANEL_PAGE = '/src/mainPanel/mainPanel.html';

// Messaging
export const Messages = Object.freeze({
    FROM_MAIN_PANEL: 'FROM_IFRAME',
    FROM_CONTROLLER: 'FROM_CONTROLLER',
    SELECT_ELEMENTS: 'SELECT_ELEMENTS',
    SELECTED: 'SELECTED',
    UNSELECTED: 'UNSELECTED',
    DECIDE_AUTO_SELECT: 'DECIDE_AUTO_SELECT',
    ACCEPT_AUTO_SELECT: 'ACCEPT_AUTO_SELECT',
    REJECT_AUTO_SELECT: 'REJECT_AUTO_SELECT',
    ZOOM_IN: 'ZOOM_IN',
    ZOOM_OUT: 'ZOOM_OUT',
    ZOOM_PREV: 'ZOOM_PREV',
    ZOOM_NEXT: 'ZOOM_NEXT',
    TEXT_SEARCH_CONTAINS: 'TEXT_SEARCH_CONTAINS',
    TEXT_SEARCH_STARTS: 'TEXT_SEARCH_STARTS',
    TEXT_SEARCH_ENDS: 'TEXT_SEARCH_ENDS',
    BROWSER_ACTION_CLICKED: 'BROWSER_ACTION_CLICKED',
    TAB_UPDATED: 'TAB_UPDATED'
});
