// Files
export const MAIN_PANEL_PAGE = '/src/mainPanel/mainPanel.html';
export const DATA_PREVIEW = '/src/contentScripts/previewTable/previewTable.html';

// Messaging
export const Messages = Object.freeze({
    FROM_MAIN_PANEL: 'FROM_IFRAME',
    FROM_CONTROLLER: 'FROM_CONTROLLER',
    MINIMIZE_MAXIMIZE: 'MINIMIZE_MAXIMIZE',
    SWITCH_SIDES: 'SWITCH_SIDES',
    SELECTING_ROWS: 'SELECTING_ROWS',
    SELECTING_COLS: 'SELECTING_COLS',
    ADDED_COL: 'ADDED_COL',
    RENAMED_COL: 'RENAMED_COL',
    REMOVED_COL: 'REMOVED_COL',
    CHOSEN_COL: 'CHOSEN_COL',
    SELECTING_ELEMENTS: 'SELECTING_ELEMENTS',
    UNDO: 'UNDO',
    REDO: 'REDO',
    ENABLE_UNDO: 'ENABLE_UNDO',
    ENABLE_REDO: 'ENABLE_REDO',
    DISABLE_UNDO: 'DISABLE_UNDO',
    DISABLE_REDO: 'DISABLE_REDO',
    SELECTED: 'SELECTED',
    UNSELECTED: 'UNSELECTED',
    TEXT_SEARCH_CONTAINS: 'TEXT_SEARCH_CONTAINS',
    TEXT_SEARCH_STARTS: 'TEXT_SEARCH_STARTS',
    TEXT_SEARCH_ENDS: 'TEXT_SEARCH_ENDS',
    CSS_SELECT: 'CSS_SELECT',
    CSS_UNSELECT: 'CSS_UNSELECT',
    DOWNLOAD: 'DOWNLOAD',
    DISPLAY_PREVIEW: 'DISPLAY_PREVIEW',
    BROWSER_ACTION_CLICKED: 'BROWSER_ACTION_CLICKED',
    TAB_UPDATED: 'TAB_UPDATED',
    SELECT_ALL_EMAILS: 'SELECT_ALL_EMAILS',
    SELECT_ALL_IMAGES: 'SELECT_ALL_IMAGES'
});
